# Generated by Django 3.2.3 on 2021-05-30 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 4, 7, 27, 786450)),
        ),
    ]
