# Generated by Django 3.2.3 on 2021-05-30 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_alter_machine_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='machines.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 21, 14, 42, 940206)),
        ),
    ]
