# Generated by Django 3.2.3 on 2021-05-31 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20210530_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='push_token',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 3, 34, 55, 342558)),
        ),
    ]
